services:
  app:
    container_name: backup-master-app
    build:
      dockerfile: docker/php/Dockerfile
      context: .
      target: app_prod
    extra_hosts:
      - host.docker.internal:host-gateway