services:
  app:
    build:
      context: .
      target: app_dev
    volumes:
      - .:/home/dev/backup-master
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    environment:
      XDEBUG_MODE: debug
      PHP_IDE_CONFIG: serverName=local